name: foodioo
description: "A personal project build with 21DTHC4 team."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  rename_app: ^1.6.1
  blur: ^4.0.0
  vibration: ^2.0.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  curl_logger_dio_interceptor: ^1.0.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.2.1
  get_storage: ^2.1.1
  sliding_up_panel: ^2.0.0+1
  flutter_bloc: ^8.1.6
  package_info_plus: ^8.1.0
  loader_overlay: ^4.0.3
  fluttertoast: ^8.2.8
  smooth_page_indicator: ^1.2.0+3
  toastification: ^2.3.0
  scroll_to_hide: ^2.1.0
  hidable: ^1.0.6
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  skeletonizer: ^1.4.2
  time_elapsed: ^0.3.1
  widget_to_marker: ^1.0.6
  image_picker: ^1.1.2

dev_dependencies:
  flutter_gen: ^5.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0

# bash to change app icon:v
# flutter pub get
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/avatar/app_avatar.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_gen:
  output: lib/core/theme/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/avatar/
